sut:
  build: .
  command: >
      sh -c "
        if id -u imio | grep -q '913' && date +%Z | grep -q 'CE'; then
          echo \"Tests passed!\"
          exit 0
        else
          echo \"Tests failed!\"
          exit 1
        fi
      "
