services:
  sut:
    build: .
    command: >
        sh -c "
          if which curl git jq && date +%Z | grep -q 'CE'; then
            echo \"Tests passed!\"
            exit 0
          else
            echo \"Tests failed!\"
            exit 1
          fi
        "
