name: Update images
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 15 * * 6' # Weekly on Saturdays at 15:00

env:
  IMAGE_NAME: common/base

jobs:
  actions-runner-base:
    runs-on:
      group: self-hosted
    steps:
      - name: Build push actions-runner-base and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: common/actions-runner-base
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/common/actions-runner-base:latest
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.COMMON_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.COMMON_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: actions-runner/base
          DOCKERFILE: actions-runner/base/Dockerfile
  actions-runner-django:
    runs-on:
      group: self-hosted
    needs: actions-runner-base
    steps:
      - name: Build push actions-runner-base and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: common/actions-runner-django
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/common/actions-runner-django:latest
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.COMMON_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.COMMON_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: actions-runner/django
          DOCKERFILE: actions-runner/django/Dockerfile
  actions-runner-plone-py2:
    runs-on:
      group: self-hosted
    needs: actions-runner-base
    steps:
      - name: Build push actions-runner-base and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: common/actions-runner-plone-py2
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/common/actions-runner-plone-py2:latest
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.COMMON_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.COMMON_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: actions-runner/plone/py2
          DOCKERFILE: actions-runner/plone/py2/Dockerfile
  actions-runner-plone-py3:
    runs-on:
      group: self-hosted
    needs: actions-runner-base
    steps:
      - name: Build push actions-runner-base and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: common/actions-runner-plone-py3
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/common/actions-runner-plone-py3:latest
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.COMMON_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.COMMON_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: actions-runner/plone/py3
          DOCKERFILE: actions-runner/plone/py3/Dockerfile
  py2-ubuntu-20_04:
    runs-on:
      group: self-hosted
    steps:
      - name: Build push py2-ubuntu-20.04 and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:py2-ubuntu-20.04
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.COMMON_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.COMMON_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: py2/ubuntu/20.04
          DOCKERFILE: py2/ubuntu/20.04/Dockerfile
  py2-ubuntu-22_04:
    runs-on:
      group: self-hosted
    steps:
      - name: Build push py2-ubuntu-22.04 and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:py2-ubuntu-22.04
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.COMMON_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.COMMON_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: py2/ubuntu/22.04
          DOCKERFILE: py2/ubuntu/22.04/Dockerfile

  py3-alpine:
    runs-on:
      group: self-hosted
    steps:
      - name: Build push py3-alpine and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:py3-alpine
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.COMMON_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.COMMON_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: py3/alpine
          DOCKERFILE: py3/alpine/Dockerfile

  py3-ubuntu-20_04:
    runs-on: 
      group: self-hosted
    steps:
      - name: Build push py3-ubuntu-20_04 and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:py3-ubuntu-20.04
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.COMMON_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.COMMON_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: py3/ubuntu/20.04
          DOCKERFILE: py3/ubuntu/20.04/Dockerfile

  py3-ubuntu-22_04:
    runs-on:
      group: self-hosted
    steps:
      - name: Build push py3-ubuntu-22_04 and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:py3-ubuntu-22.04
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.COMMON_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.COMMON_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: py3/ubuntu/22.04
          DOCKERFILE: py3/ubuntu/22.04/Dockerfile

  py3-ubuntu-24_04:
    runs-on:
      group: self-hosted
    steps:
      - name: Build push py3-ubuntu-24_04 and notify
        uses: IMIO/gha/build-push-notify@v3.9.3
        with:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: |
            ${{ secrets.HARBOR_URL }}/${{ env.IMAGE_NAME }}:py3-ubuntu-24.04
          REGISTRY_URL: ${{ secrets.HARBOR_URL }}
          REGISTRY_USERNAME: ${{ secrets.COMMON_HARBOR_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.COMMON_HARBOR_PASSWORD }}
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
          CONTEXT: py3/ubuntu/24.04
          DOCKERFILE: py3/ubuntu/24.04/Dockerfile
