name: Update images
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 15 * * 6' # Weekly on Saturdays at 15:00
jobs:
  py2-ubuntu-22_04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: py2-ubuntu-22.04
        uses: docker/build-push-action@v2.5.0
        with:
          context: py2/ubuntu/22.04
          tags: imiobe/base:py2-ubuntu-22.04
          platforms: linux/amd64
          pull: true
          push: true
  py3-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: py3-alpine
        uses: docker/build-push-action@v2.5.0
        with:
          context: py3/alpine
          tags: imiobe/base:py3-alpine
          platforms: linux/amd64
          pull: true
          push: true
  py3-ubuntu-22_04:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.COMMON_HARBOR_USERNAME }}
          password: ${{ secrets.COMMON_HARBOR_PASSWORD }}
      - name: py3-ubuntu-22.04
        uses: docker/build-push-action@v2.5.0
        with:
          context: py3/ubuntu/22.04
          tags: common/base:py3-ubuntu-22.04
          platforms: linux/amd64
          pull: true
          push: true
  debian-bookworm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: teleservices-bookworm-base
        uses: docker/build-push-action@v2.5.0
        with:
          context: debian/bookworm
          tags: imiobe/teleservices-bookworm-base:latest
          platforms: linux/amd64
          pull: true
          push: true
