name: Update images
on:
  push:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: -X POST ${{ secrets.DOCKER_HUB_TRIGGER_URL }}
