name: Update images
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * *' # Weekly on Sundays at 02:00
jobs:
  debian-buster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: debian-buster
        uses: docker/build-push-action@v2.5.0
        with:
          context: debian/buster
          tags: imiobe/base:debian-buster
          pull: true
          push: true
  py2-debian-buster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: py2-debian-buster
        uses: docker/build-push-action@v2.5.0
        with:
          context: py2/debian/buster
          tags: imiobe/base:py2-debian-buster
          pull: true
          push: true
  py2-ubuntu-18.04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: py2-ubuntu-18.04
        uses: docker/build-push-action@v2.5.0
        with:
          context: py2/ubuntu/18.04
          tags: imiobe/base:py2-ubuntu-18.04
          pull: true
          push: true
  py2-ubuntu-20.04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: py2-ubuntu-20.04
        uses: docker/build-push-action@v2.5.0
        with:
          context: py2/ubuntu/20.04
          tags: imiobe/base:py2-ubuntu-20.04
          pull: true
          push: true
  py3-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: py3-alpine
        uses: docker/build-push-action@v2.5.0
        with:
          context: py3/alpine
          tags: imiobe/base:py3-alpine
          pull: true
          push: true
  py3-ubuntu-20.04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: py3-ubuntu-20.04
        uses: docker/build-push-action@v2.5.0
        with:
          context: py3/ubuntu/20.04
          tags: imiobe/base:py3-ubuntu-20.04
          pull: true
          push: true
